#!/bin/bash

# rofi-power
# Use rofi to call systemctl for shutdown, reboot, etc

# 2016 Oliver Kraitschy - http://okraits.de

OPTIONS="Suspend system\nPower-off system\nReboot system\nLock\nLogout\nWifi\nSound\nBluetooth_toggle\nBluetooth_options\nEnergy_management Disable"

# source configuration or use default values
if [ -f $HOME/.config/rofi-power/config ]; then
  source $HOME/.config/rofi-power/config
else
  LAUNCHER="rofi -width 30 -dmenu -i -p rofi-power:"
fi

# Show exit wm option if exit command is provided as an argument
if [ ${#1} -gt 0 ]; then
  OPTIONS="Exit window manager\n$OPTIONS"
fi

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $1}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]
then
    case $option in
      Exit)
        eval $1
        ;;
      Reboot)
        systemctl reboot
        ;;
      Lock)
        lock
        ;;
      Power-off)
        systemctl poweroff
        ;;
      Suspend)
        lock; systemctl suspend
        ;;
      Logout)
        i3-msg exit
        ;;
      Wifi)
	      nm-applet
	      ;;
      Sound)
	      pavucontrol
        ;;
      Bluetooth_toogle)
	      sudo ~/dots/scripts/toggle_bluetooth
	      ;;
      Bluetooth_options)
      	blueman-manager
      	;;
      Energy_management)
      	xset -dpms
        xset s off
      	;;
      *)
        ;;
    esac
fi
